### ISSUE TITLE
📝 Add some information to the readme

### ISSUE THREAD

**Issue by Ked57** [Zenika/alibeez-to-google-calendar-connector#13]
- [X] document environment variables (see for example https://github.com/Zenika/platon/blob/master/.env.example)
 - [X] describe how to init a user
 - [X] describe how authentication to Google works
 - [x] inform that an Alibeez test instance is available to test the connector

**Comment by hgwood** [comment]
I consider the last point done with the mention "ask dreamlab@zenika.com for working values"
